    <tfoot>
        <tr>
            <th>廳次</th>
            <th>日期</th>
            <th>時間</th>
            <th>電影</th>
            <th>數量</th>
            <th>價錢</th>
            <th>購買紀錄</th>
        </tr>
    </tfoot>
</tbody>
</table>
</div>
<script>
    $('#mytable').dataTable();
</script>
